trigger:
  - master

variables:
  buildPlatform: 'x64'
  testAssembliesSearchPattern: 'BuildTest\**\CntkCatalyst.Test.dll'

jobs:
- job: 'CI'
  displayName: 'CI'
  pool:
    name: Hosted VS2017
    
  strategy:
    matrix:
      Debug:
        buildConfiguration: 'Debug'
      Release:
        buildConfiguration: 'Release'
  
  steps:
  - task: NuGetCommand@2
    displayName: 'NuGet Restore'
    inputs:
      restoreSolution: '**\*.sln'
      nugetConfigPath: nuget.config
  
  - task: VSBuild@1
    displayName: 'Build solution **\*.sln'
    inputs:
      vsVersion: 15.0
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
  
  - task: VSTest@2
    displayName: 'Test Assemblies'
    inputs:
      testAssemblyVer2: |
          $(testAssembliesSearchPattern)
          !**\*TestAdapter*.dll
          !**\*.Testing.dll
          !**\*IntegrationTests*.dll
          !**\*TestFramework*.dll
          !**\obj\**
      vsTestVersion: toolsInstaller
      runInParallel: true
      runTestsInIsolation: true
      codeCoverageEnabled: true
      otherConsoleOptions: '/Platform:$(buildPlatform)' # E.g. to force running as x64
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  
  - task: NuGetCommand@2
    displayName: 'NuGet Package'
    inputs:
      command: 'pack'
      configuration: '$(buildConfiguration)'
      buildProperties: 'Platform=$(buildPlatform)'
      packDestination: '$(Build.ArtifactStagingDirectory)'
      packagesToPack: 'src/CntkCatalyst/CntkCatalyst.csproj'
    condition: and(succeeded(), eq(variables['buildConfiguration'], 'Release'))
    
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: 'nuget/mdabros'
    enabled: true
    condition: and(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')), eq(variables['buildConfiguration'], 'Release'))
 
